### ISSUE TITLE
Missing library in gettext.h

### ISSUE THREAD

**Issue by ricks03** [lbernstone/rrdtool_ESP32#1]
I'm currently running an Arduino Uno with the 1.8.13 compiler. 

Using "Manage Libraries" I searched for and added rrdtool by Larry Bernstone version 1.0.0

that done, I use the Tools > Include Library > RRD, and the following libraries are added to my sketch:
#include <fnv.h>
#include <gettext.h>
#include <plbasename.h>
#include <rrd.h>
#include <rrd_config.h>
#include <rrd_config_bottom.h>
#include <rrd_format.h>
#include <rrd_getopt.h>
#include <rrd_hw.h>
#include <rrd_hw_math.h>
#include <rrd_hw_update.h>
#include <rrd_i18n.h>
#include <rrd_is_thread_safe.h>
#include <rrd_parsetime.h>
#include <rrd_rpncalc.h>
#include <rrd_tool.h>
#include <rrd_xport.h>
#include <strftime.h>
#include <unused.h>

Attempting to compile the sketch, I get the following error: 
Arduino: 1.8.13 (Windows 7), Board: "Arduino Uno"
In file included from D:\Arduino\flowmeter4\flowmeter4.ino:46:0:
C:\\Arduino\libraries\rrdtool\src/gettext.h:56:11: fatal error: cstdlib: No such file or directory
 # include <cstdlib>
           ^~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

which looks like gettext.h requires cstdlib ? I don't see that library included (or searchable) in the libraries.

**Comment by lbernstone** [comment]
There is probably an error somewhere up there saying "selected board is not supported".  This library only works on esp32.  Uno is missing about half the operating system needed for this library.
