### ISSUE TITLE
Question about writes...

### ISSUE THREAD

**Issue by mike-s123** [lbernstone/rrdtool_ESP32#2]
I'm using this to update an rrd on an SD card. My concern is the number of physical writes which happen, which causes wear on the card.

I though of buffering updates myself, then doing a bunch of rrd_update_r calls, but since you open and close the file for each update, I don't think that really helps. It would be nice to have a way to have rrdtool_ESP32 keep the file open until something like a flush is asked for. I don't pretend to know the best way to do that.

Comments?

**Comment by lbernstone** [comment]
Unfortunately, there is no mechanism for vmem in esp32, which would provide some method for this in conjunction with psram.  In later versions of rrdtool, there is a cache daemon which would provide this capability, but it requires glib, which has some pieces (esp iconv) which are not currently implemented in the toolchain.  I'll post my progress on this in a branch if you want to take a look.

**Comment by mike-s123** [comment]
Thanks for taking a look and thinking about it. It's above my level.

**Comment by lbernstone** [comment]
I just uploaded some examples that should address your issue.  In the basicDB example, fakeData now shows how to insert multiple data points in one pass. In the psram example, I show how you can work entirely in a memory datastore, and then back up to flash on a schedule.  This means you can absolutely control how many writes occur, and improves overall performance at the same time.  It also means you can use littlefs for improved data integrity.

**Comment by mike-s123** [comment]
Thanks. I saw the ESP32-PsRamFS from @tobozo and had started playing with it. Your example made it easier to get it working. When I get stuff changed over, I shouldn't have to worry about wearing out SD cards anymore.
